### ISSUE TITLE
Make hero and flexslider versions with <img> elements

### ISSUE THREAD

**Issue by adamglenn** [wvuweb/wvu-brand-patterns-theme#11]
Rather than have hero unit photos as background images, we need another version that allows users to insert images within the HTML itself. This will make it easier for users to add photos who don't know CSS.

**Comment by zeroedin** [comment]
Would that be something better served as a slate snippet?  Curious on your thoughts of how you think that would work?  Shouldn't the user be loading the images via a tag?
