### ISSUE TITLE
Where should the logo link to?

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/wvu-brand-patterns-theme#7]
In all of your masthead examples, the logo is linking to http://www.wvu.edu. Should the logo's link to their respective site's homepages? For example, on http://patterns.sandbox.wvu.edu/ if you click the logo, it takes you to `wvu.edu` instead of taking you to the "Digital Services" homepage. 

IMO, logo's should link to their individual homepages instead of wvu.edu.

Related:

https://ux.stackexchange.com/questions/5003/home-button-vs-logo-link

**Comment by adamglenn** [comment]
The logo now links to the site root, which is where it should go.
